common: bin: update remarkable2-stream script
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

diff --git a/common/.local/bin/remarkable2-stream b/common/.local/bin/remarkable2-stream
--- a/common/.local/bin/remarkable2-stream
+++ b/common/.local/bin/remarkable2-stream
@@ -7,6 +7,8 @@ output_path=-              # display output through ffplay
 format=-                   # automatic output format
 webcam=false               # not to a webcam
 measure_throughput=false   # measure how fast data is being transferred
+window_title=reStream      # stream window title is reStream
+video_filters=""           # list of ffmpeg filters to apply
 
 # loop through arguments and process them
 while [ $# -gt 0 ]; do
@@ -30,7 +32,7 @@ while [ $# -gt 0 ]; do
             shift
             shift
             ;;
-        -t | --throughput)
+        -m | --measure)
             measure_throughput=true
             shift
             ;;
@@ -55,8 +57,13 @@ while [ $# -gt 0 ]; do
             fi
             shift
             ;;
+        -t | --title)
+            window_title="$2"
+            shift
+            shift
+            ;;
         -h | --help | *)
-            echo "Usage: $0 [-p] [-s <source>] [-o <output>] [-f <format>]"
+            echo "Usage: $0 [-p] [-s <source>] [-o <output>] [-f <format>] [-t <title>]"
             echo "Examples:"
             echo "	$0                              # live view in landscape"
             echo "	$0 -p                           # live view in portrait"
@@ -69,47 +76,58 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-# technical parameters
-width=1408
-height=1872
-bytes_per_pixel=2
-loop_wait="true"
-loglevel="info"
-
 ssh_cmd() {
-    ssh -o ConnectTimeout=1 "$ssh_host" "$@"
+    echo "[SSH]" "$@" >&2
+    ssh -o ConnectTimeout=1 -o PasswordAuthentication=no "$ssh_host" "$@"
 }
 
 # check if we are able to reach the remarkable
 if ! ssh_cmd true; then
-    echo "$ssh_host unreachable"
+    echo "$ssh_host unreachable or you have not set up an ssh key."
+    echo "If you see a 'Permission denied' error, please visit"
+    echo "https://github.com/rien/reStream/#installation for instructions."
     exit 1
 fi
 
-fallback_to_gzip() {
-    echo "Falling back to gzip, your experience may not be optimal."
-    echo "Go to https://github.com/rien/reStream/#sub-second-latency for a better experience."
-    compress="gzip"
-    decompress="gzip -d"
-    sleep 2
-}
+rm_version="$(ssh_cmd cat /sys/devices/soc0/machine)"
 
-# check if lz4 is present on remarkable
-if ssh_cmd "[ -f /opt/bin/lz4 ]"; then
-    compress="/opt/bin/lz4"
-elif ssh_cmd "[ -f ~/lz4 ]"; then
-    compress="\$HOME/lz4"
+case "$rm_version" in
+    "reMarkable 1.0")
+        width=1408
+        height=1872
+        pixel_format="rgb565le"
+        ;;
+    "reMarkable 2.0")
+        pixel_format="gray8"
+        width=1872
+        height=1404
+        video_filters="$video_filters,transpose=2"
+        ;;
+    *)
+        echo "Unsupported reMarkable version: $rm_version."
+        echo "Please visit https://github.com/rien/reStream/ for updates."
+        exit 1
+        ;;
+esac
+
+# technical parameters
+loglevel="info"
+decompress="lz4 -d"
+
+# check if lz4 is present on the host
+if ! lz4 -V >/dev/null; then
+    echo "Your host does not have lz4."
+    echo "Please install it using the instruction in the README:"
+    echo "https://github.com/rien/reStream/#installation"
+    exit 1
 fi
 
-# gracefully degrade to gzip if is not present on remarkable or host
-if [ -z "$compress" ]; then
-    echo "Your remarkable does not have lz4."
-    fallback_to_gzip
-elif ! lz4 -V >/dev/null; then
-    echo "Your host does not have lz4."
-    fallback_to_gzip
-else
-    decompress="lz4 -d"
+# check if restream binay is present on remarkable
+if ssh_cmd "[ ! -f ~/restream ]"; then
+    echo "The restream binary is not installed on your reMarkable."
+    echo "Please install it using the instruction in the README:"
+    echo "https://github.com/rien/reStream/#installation"
+    exit 1
 fi
 
 # use pv to measure throughput if desired, else we just pipe through cat
@@ -125,48 +143,30 @@ else
     host_passthrough="cat"
 fi
 
-# list of ffmpeg filters to apply
-video_filters=""
-
 # store extra ffmpeg arguments in $@
 set --
-
-# calculate how much bytes the window is
-window_bytes="$((width * height * bytes_per_pixel))"
 
 # rotate 90 degrees if landscape=true
 $landscape && video_filters="$video_filters,transpose=1"
 
 # Scale and add padding if we are targeting a webcam because a lot of services
 # expect a size of exactly 1280x720 (tested in Firefox, MS Teams, and Skype for
-# for business). Send a PR is you can get a heigher resolution working.
+# for business). Send a PR if you can get a higher resolution working.
 if $webcam; then
     video_filters="$video_filters,format=pix_fmts=yuv420p"
-    if $landscape; then
-        render_width=$((720 * height / width))
-    else
-        render_width=$((720 * width / height))
-    fi
-
-    # center
-    offset_left=$(((1280 - render_width) / 2))
-    video_filters="$video_filters,scale=${render_width}x720"
-    video_filters="$video_filters,pad=1280:720:$offset_left:0:#eeeeee"
+    video_filters="$video_filters,scale=-1:720"
+    video_filters="$video_filters,pad=1280:0:-1:0:#eeeeee"
 fi
 
 # set each frame presentation time to the time it is received
 video_filters="$video_filters,setpts=(RTCTIME - RTCSTART) / (TB * 1000000)"
 
-# read the first $window_bytes of the framebuffer
-head_fb0="dd if=/dev/fb0 count=1 bs=$window_bytes 2>/dev/null"
-
-# loop that keeps on reading and compressing, to be executed remotely
-read_loop="while $head_fb0; do $loop_wait; done | $compress"
-
 set -- "$@" -vf "${video_filters#,}"
 
 if [ "$output_path" = - ]; then
     output_cmd=ffplay
+
+    window_title_option="-window_title $window_title"
 else
     output_cmd=ffmpeg
 
@@ -180,14 +180,15 @@ fi
 set -e # stop if an error occurs
 
 # shellcheck disable=SC2086
-ssh_cmd "$read_loop" \
+ssh_cmd "./restream" \
     | $decompress \
     | $host_passthrough \
     | "$output_cmd" \
         -vcodec rawvideo \
         -loglevel "$loglevel" \
         -f rawvideo \
-        -pixel_format rgb565le \
+        -pixel_format "$pixel_format" \
         -video_size "$width,$height" \
+        $window_title_option \
         -i - \
         "$@"
